source 'https://cdn.cocoapods.org/'
use_frameworks!

platform :ios, '10.0'

target 'BowLiteCore_Example' do
  pod 'BowLiteCore', :path => '../'

  target 'BowLiteCore_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.0'
    pod 'Nimble', '~> 8.0'
  end
end
